### ISSUE TITLE
Definition of Tmat

### ISSUE THREAD

**Issue by maxthilo** [DylanB95/statespacer#5]
Hi Dylan!

On https://dylanb95.github.io/statespacer/articles/selfspec.html

you write 

Tmat <- cbind(Tmat, diag(1, 3, 3) - Tmat)

Why the "- Tmat" in the second part? I would have just written "cbind(Tmat, diag(1,3,3)" so that a_1,t+1 does not load on the means of factor 2 + 3?

**Comment by DylanB95** [comment]
Hi Max, 

It's a matter of definition. By doing it this way, the mean of the factors equals mu. If you didn't include -Tmat, like you propose, the mean of the factors would equal mu + Phi*mu

Kind regards,
Dylan
