### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by chongsumyi** [DylanB95/statespacer#6]
Hi, 

When I was using the state space function, this error: _Error in diag(1, p, p): invalid 'nrow' value (too large or NA) keeps popping up. 

However, there are no missing values in my dataset and my dataset is very similar to the one used as an example here: https://dylanb95.github.io/statespacer/articles/intro.html (i.e., y <- [matrix](Nile))

I'm not sure what happened and how to fix this error. Thank you for your help!

**Comment by DylanB95** [comment]
Hi,

Could you run dim(y) and share its output?

**Comment by chongsumyi** [comment]
[1] 78  1

**Comment by DylanB95** [comment]
Could you share the code you use to call the statespacer function?

**Comment by chongsumyi** [comment]
For sure. Thanks for your help!

ML01 <- read.csv ("01.csv", header = TRUE, sep = ",")
y <- ML01

fit <- statespacer(y = y$DirErr,
                   local_level_ind = TRUE,
                   initial = 0.5*log(var(y)))

**Comment by DylanB95** [comment]
What about dim(y$DirErr)? Could you share its output?

**Comment by chongsumyi** [comment]
it's Null

**Comment by DylanB95** [comment]
That explains it. The y argument expects a matrix, doing the following should work.

fit <- statespacer(y = matrix(y$DirErr),
local_level_ind = TRUE,
initial = 0.5*log(var(y)))

**Comment by chongsumyi** [comment]
Great! Thank you so much for your help, Dylan.

**Comment by DylanB95** [comment]
No problem, good luck!
