### ISSUE TITLE
Additional examples of self-specified models

### ISSUE THREAD

**Issue by gueyenono** [DylanB95/statespacer#8]
First and foremost, thank you very much for a very wonderful and accessible package for state-space models.
Currently, I am able to use the package for most (if not all) traditional state-space specifications, however, I would like to learn how to manually build a model with the package. Even though I went through the example in:

https://dylanb95.github.io/statespacer/articles/selfspec.html

I still find it fairly complicated to grasp since I am not really familiar with the Nelson-Siegel model (I plan on reading the paper specified in the article at a later time). Would it be possible to also show how to manually specify the UK seatbelts models used in the first few articles. I believe that understanding the basics could enable the users to build on them to construct more complicated models.

Thank you.

**Comment by DylanB95** [comment]
I might add such an example later, but in essence it's a matter of passing along the system matrices of the model you're interested in. And then there's a split between parameter dependent system matrices and fixed system matrices. Reason for that is to let the optimisation routine know which matrices need to be recomputed when maximising the log likelihood. 

Kind regards, 
Dylan

**Comment by gueyenono** [comment]
Thank you for your prompt reply. I think your design choices for the functions of the package are very optimal and intuitive. Kudos to you once again. I will be patiently awaiting for when you have some free time for the examples. Also, the names of the elements in the `self_spec_list`, I take it that the `statespacer` function looks for these names specifically, right? Also, are there other components that could be added to the list which are not used in the article? Once again, I'll be on the lookout for additional examples. Thank you.

**Comment by DylanB95** [comment]
Indeed, the elements should have specific names that the function looks for. See the Details section for all the elements that can be passed on: https://dylanb95.github.io/statespacer/reference/statespacer.html

**Comment by gueyenono** [comment]
This is well noted. Thank you very much once again for a great package!
